from typing import Protocol

from app.models.department import Department


class DepartmentRepository(Protocol):
    async def save(self, department: Department) -> None: ...
    async def get(self, department_id: str) -> Department | None: ...
    async def get_all(self) -> list[Department]: ...
    async def update(self, department: Department) -> None: ...
