from typing import Protocol

from app.models.department import Department


class DepartmentRepository(Protocol):
    def save(self, department: Department) -> None: ...
    def get(self, department_id: str) -> Department | None: ...
    def get_all(self) -> list[Department]: ...
    def update(self, department: Department) -> None: ...
