from typing import Protocol


class ImageStore(Protocol):
    async def upload_image(self, image_data: bytes, name: str) -> str: ...
    async def delete_image(self, image_url: str) -> None: ...
    async def get_image_download_url(self, image_url: str) -> str: ...
