from typing import IO, Protocol


class ImageStore(Protocol):
    async def upload_image(self, name: str, image: IO) -> str: ...
    async def delete_image(self, image_url: str) -> None: ...
    async def get_image_download_url(self, image_url: str) -> str: ...
