from typing import Protocol

from app.models.project import Project


class ProjectRepository(Protocol):
    async def save(self, project: Project) -> None: ...
    async def get(self, project_id: str) -> Project | None: ...
    async def get_all(self) -> list[Project]: ...
    async def update(self, project: Project) -> None: ...
