from typing import Protocol

from app.models.project import Project


class ProjectRepository(Protocol):
    def save(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Project | None: ...
    def get_all(self) -> list[Project]: ...
    def update(self, project: Project) -> None: ...
