from typing import Protocol

from app.models.user import User


class UserRepository(Protocol):
    def save(self, user: User) -> None: ...
    def get(self, user_id: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_all(self) -> list[User]: ...
    def delete(self, user_id: str) -> None: ...
    def update(self, user: User) -> None: ...
