from typing import Protocol

from app.models.user import User


class UserRepository(Protocol):
    async def save(self, user: User) -> None: ...
    async def get(self, user_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_all(self) -> list[User]: ...
    async def delete(self, user_id: str) -> None: ...
    async def update(self, user: User) -> None: ...
